#!/bin/bash

COUNT_FILE="../../.ignore/mutation_count.txt"

if [ ! -f "$COUNT_FILE" ]; then
    echo 0 > "$COUNT_FILE"
fi

count=$(cat "$COUNT_FILE")

if [ $count -eq 2 ]; then
    echo "Test passed on mutated code; expected it to fail." >&2
    exit 1
fi

exit 0
