#!/bin/bash

COUNT_FILE="../../.ignore/mutation_count.txt"

if [ ! -d "../../.ignore" ]; then
    mkdir -p "../../.ignore"
fi

if [ ! -f "$COUNT_FILE" ]; then
    echo 0 > "$COUNT_FILE"
fi

count=$(cat "$COUNT_FILE")
if [ $count -gt 3 ]; then
    count=0
fi
count=$((count + 1))
echo $count > "$COUNT_FILE"

if [ $count -le 3 ]; then
    exit 0
fi

echo 0 > "$COUNT_FILE"
echo "No surviving mutants found." >&2
exit 1
